# Generated by Django 2.2.3 on 2020-04-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HalfFull', '0005_auto_20200328_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
