# Generated by Django 2.2.3 on 2020-04-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HalfFull', '0005_auto_20200328_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('current_crawl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='HalfFull.Pub')),
                ('pubs', models.ManyToManyField(to='HalfFull.Pub')),
            ],
        ),
    ]
