# Generated by Django 2.2.3 on 2020-04-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HalfFull', '0006_pub_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='slug',
        ),
    ]
