# Generated by Django 2.2.3 on 2020-04-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HalfFull', '0006_crawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crawl',
            field=models.ManyToManyField(to='HalfFull.Pub'),
        ),
        migrations.DeleteModel(
            name='Crawl',
        ),
    ]
